version: '2.3'
services:
  maskrcnn:
    image: yubaoliu/maskrcnn:cuda9.0-ubuntu16
    build:
        context: .
        args:
            cuda_version: 9.0
            cudnn_version: 7
            ubuntu_version: 16.04
    container_name: maskrcnn_cuda9.0_ubuntu16
    runtime: nvidia
    # stdin_open: true
    # tty: true
    command: roscore
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ..:/root/MaskRCNN
        - ${CNN_MODEL_DIR}:/root/MaskRCNN/model
        - ${DATASET_DIR}:/root/Dataset
        - maskrcnn_root:/root
    cap_add:
        - SYS_PTRACE
    # ports:
        # - ${PORT}:8888
    # privileged: true
    entrypoint: /entrypoint.sh
    network_mode: host

volumes:
    maskrcnn_root:
