version: '2.3'
services:
  ubuntu20-cuda11.3.0:
    image: yubao/ubuntu20:cuda11.3.0
    # container_name: root_ros_noetic
    build:
        context: ..
        dockerfile: Ubuntu20/Dockerfile
        args:
            CUDA_VERSION: 11.3.0
            ROS_DISTRO: noetic
            CUDNN_VERSION: cudnn8
            # cudnn_version: 7
            # ubuntu_version: 16.04
    runtime: nvidia
    stdin_open: true
    tty: true
    privileged: true
    command:
        # - xterm
        - lxterminal
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
    devices:
        - /dev/dri
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ~/.Xauthority:/root/.Xauthority
        # - /usr/lib/nvidia-cuda-toolkit:/usr/lib/nvidia-cuda-toolkit
        # - yubao_ubuntu20_cuda11:/root

# volumes:
#     yubao_ubuntu20_cuda11:
