FROM yubaoliu/root:ros-cuda10.2-cudnn7-ubuntu16


COPY ./install.sh /root/

RUN bash -c "/root/install.sh"

COPY ./entrypoint.sh /
RUN chmod 777 /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

CMD ["bash"]

# # Install dependencies
# # Newer CUDA was installed in base image, so rosdep keys of CUDA are skipped
# RUN /bin/bash -c "source /opt/ros/kinetic/setup.bash && \
#                   rosdep install --from-paths src -r -y --skip-keys=\"nvidia-cuda-dev nvidia-cuda\""
#                   
# # Build
# RUN /bin/bash -c "source /opt/ros/kinetic/setup.bash && \
#                   catkin_make -DCMAKE_BUILD_TYPE=Release"
# 
# # Load ROS environment at each run


