version: '2.3'
services:
  ubuntu16_cuda10_ros:
    image: yubaoliu/root:ros-cuda10.2-cudnn7-ubuntu16.04
    build:
        context: .
        dockerfile: Dockerfile
        args:
            cuda_version: 10.2
            nvidia_cudnn_version: 7.6.5.32-1+cuda10.2
            ubuntu_version: 16.04
    runtime: nvidia
    command:
        - roscore
    stdin_open: true
    tty: true
    privileged: true
    network_mode: "host"
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ubuntu16_cuda10.2_ros:/root
    # entrypoint: /entrypoint-kinetic.sh

volumes:
    ubuntu16_cuda10.2_ros:
