version: '2.3'
services:
  ubuntu18-cuda12-0-1:
    image: slamai/ubuntu18:cuda12.0.1
    container_name: ubuntu18
    build:
        context: ..
        dockerfile: Ubuntu18/Dockerfile
        args:
            CUDA_VERSION: 12.0.1
            CUDNN_VERSION: cudnn8
            ROS_DISTRO: melodic
            VSCODE_COMMIT_ID: 8b3775030ed1a69b13e4f4c628c612102e30a681
            # http_proxy: ${HTTP_PROXY}
            # https_proxy: ${HTTPS_PROXY}
            # ubuntu_version: 16.04
    runtime: nvidia
    stdin_open: true
    tty: true
    network_mode: host
    privileged: true
    command:
        # - xterm
        - lxterminal
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
        # - http_proxy=${HTTP_PROXY}
        # - https_proxy=${HTTPS_PROXY}
    devices:
        - /dev/dri
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ~/.Xauthority:/root/.Xauthority
        # - ubuntu18_cuda11-4-2:/root
        # - /usr/lib/nvidia-cuda-toolkit:/usr/lib/nvidia-cuda-toolkit
        # - ~/Project/docker/Extern:/root/Extern
        # - ~/.vscode/extensions:/root/.vscode/extensions
        # - ~/.vimrc:/root/.vimrc
        # - ~/.vim:/root/.vim
        # - ~/.tmux.conf:/root/.tmux.conf
        # - yubao_ubuntu18_cuda11:/root
    dns:
      - 8.8.8.8
      - 8.8.4.4
# volumes:
#     yubao_ubuntu18_cuda11:
