FROM yubaoliu/root:ros-cuda10.2-cudnn7-ubuntu18

# coco API
RUN pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI

# Install mask rcnn dependencies
COPY requirements.txt /root/requirements.txt
RUN  pip3 install --force-reinstall -r /root/requirements.txt

# Install mask rcnn
RUN git clone https://github.com/yubaoliu/Mask_RCNN.git \
    && cd Mask_RCNN \
    && python setup.py install

# # Install dependencies
# # Newer CUDA was installed in base image, so rosdep keys of CUDA are skipped
# RUN /bin/bash -c "source /opt/ros/melodic/setup.bash && \
#                   rosdep install --from-paths src -r -y --skip-keys=\"nvidia-cuda-dev nvidia-cuda\""
#                   
# # Build
# RUN /bin/bash -c "source /opt/ros/melodic/setup.bash && \
#                   catkin_make -DCMAKE_BUILD_TYPE=Release"
# 
# # Load ROS environment at each run
COPY ./entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]
