version: '2.3'
services:
  ubuntu16-cuda11.3.0:
    image: slamai/ubuntu16:cuda11.3.0
    container_name: ubuntu16
    build:
        context: ..
        dockerfile: Ubuntu16/Dockerfile
        args:
            CUDA_VERSION: 11.3.0
            CUDNN_VERSION: cudnn8
            ROS_DISTRO: kinetic
            # ubuntu_version: 16.04
    runtime: nvidia
    stdin_open: true
    tty: true
    privileged: true
    command:
        - xterm
        # - lxterminal
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
    devices:
        - /dev/dri
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ~/.Xauthority:/root/.Xauthority
        - ~/dotfile:/root/dotfile
        # - /usr/lib/nvidia-cuda-toolkit:/usr/lib/nvidia-cuda-toolkit
        # - yubao_ubuntu16_cuda11:/root

# volumes:
#     yubao_ubuntu16_cuda11:
