version: '2.3'
services:
  orbslam:
    image: yubaoliu/orbslam:latest
    build:
        context: .
    container_name: orbslam
    network_mode: host
    stdin_open: true
    tty: true
    # command: bash
    runtime: nvidia
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ${DATASET_DIR}:/root/Dataset
        - orbslam:/root
    cap_add:
        - SYS_PTRACE
    privileged: true

  ros_master:
    image: yubaoliu/orbslam:latest
    command: roscore
    network_mode: host

volumes:
    orbslam:


