version: '2.3'
services:
  NormalUsage:
    image: yubao/normal_usage
    # container_name: root_ros_noetic
    build:
        context: ..
        dockerfile: NormalUsage/Dockerfile
    runtime: nvidia
    stdin_open: true
    tty: true
    privileged: true
    command:
        # - xterm
        - lxterminal
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
    devices:
        - /dev/dri
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ~/.Xauthority:/home/ubuntu/.Xauthority
        - ~/Tempt/.vim:/home/ubuntu/.vim
        - ~/.vscode:/home/ubuntu/.vscode
        - normal_usage:/home/ubuntu
        # - /usr/lib/nvidia-cuda-toolkit:/usr/lib/nvidia-cuda-toolkit
        # - yubao_ubuntu20_cuda11:/root

volumes:
  normal_usage:
