version: '2.3'
services:
  maskrcnn:
    image: maskrcnn:latest
    build: 
        context: .
        args:
            cuda_version: 9.0
            cudnn_version: 7
            ubuntu_version: 16.04
    container_name: MaskRcnn
    runtime: nvidia
    command: [bash]
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
