version: '2.3'
services:
  ubuntu18-cuda11-4-2:
    image: yubao/ubuntu18:cuda11.4.2
    # container_name: root_ros_noetic
    build:
        context: .
        dockerfile: Dockerfile
        args:
            CUDA_VERSION: 11.4.2-cudnn8
            ROS_DISTRO: melodic
            # http_proxy: ${HTTP_PROXY}
            # https_proxy: ${HTTPS_PROXY}
            # CUDNN_VERSION: 7
            # cudnn_version: 7
            # ubuntu_version: 16.04
    runtime: nvidia
    stdin_open: true
    tty: true
    network_mode: host
    privileged: true
    command:
        - lxterminal
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
        # - http_proxy=${HTTP_PROXY}
        # - https_proxy=${HTTPS_PROXY}
    devices:
        - /dev/dri
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ~/.Xauthority:/root/.Xauthority
        - ubuntu18_cuda11-4-2:/root
        # - /usr/lib/nvidia-cuda-toolkit:/usr/lib/nvidia-cuda-toolkit
        # - root:/root_yubao_ubuntu20_cuda11
    dns:
      - 8.8.8.8
      - 8.8.4.4
volumes:
    ubuntu18_cuda11-4-2:
