version: '2.3'
services:
  terminal:
    image: yubaoliu/root:ros-cuda10.2-cudnn7-ubuntu16
    container_name: myterminal
    command: xterm
    runtime: nvidia
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - root:/root

volumes:
    root:
