version: '2.3'
services:
  ros_master:
    image: yubaoliu/root:ros-cuda10.2-cudnn7-ubuntu16
    build:
        context: .
        dockerfile: dockerfile-ubuntu16
        args:
            cuda_version: 10.2
            cudnn_version: 7
            ubuntu_version: 16.04
    volumes:
        - root:/root

volumes:
    root:
