version: '2.3'

networks:
  ros:
      driver: "bridge"

services:
  ros_master:
    image: yubaoliu/root:ros-cuda10.2-cudnn7-ubuntu18
    ports:
        - 11311
    build:
        context: .
        args:
            cuda_version: 10.2
            cudnn_version: 7
    container_name: master
    command: roscore
    volumes:
        - tmproot:/root
    network_mode: host

  tum-dataset:
    image: yubaoliu/root:ros-cuda10.2-cudnn7-ubuntu18
    depends_on:
        - ros_master
    container_name: tum-dataset
    command:  rosbag play --clock -l  /root/Dataset/TUM/freiburg3/rgbd_dataset_freiburg3_walking_xyz.bag
    runtime: nvidia
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
        - ROS_HOSTNAME=tum-dataset
        - ROS_MASTER_URI=http://ros_master:11311
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ${DATASET_DIR}:/root/Dataset
        - tmproot:/root
    network_mode: service:ros_master

  terminal:
    image: yubaoliu/root:ros-cuda10.2-cudnn7-ubuntu18
    container_name: terminal
    depends_on:
      - ros_master
    command: lxterminal
    runtime: nvidia
    privileged: true
    environment: 
      - ROS_HOSTNAME=terminal
      - ROS_MASTER_URI=http://ros_master:11311
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - tmproot:/root
      - ${DATASET_DIR}:/root/Dataset
    network_mode: service:ros_master

volumes:
    tmproot:
