version: '2.3'
services:
  ros_master:
    image: yubaoliu/root:ros-cuda10.2-cudnn7-ubuntu16
    ports:
        - 11311:11311
    build:
        context: .
        dockerfile: dockerfile-ubuntu16
        args:
            cuda_version: 10.2
            cudnn_version: 7
            ubuntu_version: 16.04
    container_name: ros_master
    command: roscore
    volumes:
        - tmproot:/root

  ros-cuda10.2-cudnn7-ubuntu16:
    image: yubaoliu/root:ros-cuda10.2-cudnn7-ubuntu16
    depends_on:
        - ros_master
    container_name: ros-cuda-cudnn7-ubuntu16
    command: lxterminal
    runtime: nvidia
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
        - ROS_HOSTNAME=ros-cuda-cudnn7-ubuntu16
        - ROS_MASTER_URI=http://ros_master:11311
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ..:/root/data
        - tmproot:/root

volumes:
    tmproot:
