# versiion
ARG cuda_version=9.0
ARG cudnn_version=7
ARG ubuntu_version=16.04

FROM nvidia/cuda:${cuda_version}-cudnn${cudnn_version}-devel-ubuntu${ubuntu_version}

# base image
MAINTAINER yubaoliu89@gmail.com

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8


# Setup timezone
RUN echo 'Etc/UTC' > /etc/timezone && \
    rm /etc/localtime && \
    ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
    apt-get update && apt-get install -y tzdata

# Install tools for development
RUN apt-get update && \
    apt-get install -y vim \
    sudo \
    byobu \
    gdb \
    htop \
    lxterminal \
    tmux \
    wget \
    git \
    openssh-server \
    curl \
    zip \
    unzip \
    g++ \
    graphviz \
    trash-cli \
    libevent-dev \
    bison \
    byacc \
    autotools-dev \
    automake \
    zsh \
    vim-gtk  #vim clipboard 
   
# Python
RUN apt-get update && \
    apt-get install -y python3-pip \
    python3-dev
 
COPY ./userconfig.sh /root/userconfig.sh

#update pip
RUN curl -kL https://bootstrap.pypa.io/get-pip.py | python3 

# Install packages to add ROS repository
RUN apt-get install -y dirmngr gnupg2
# Add ROS repository
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-latest.list'
# Keys for ROS repository
RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
# Install ROS bootstrap tools
RUN apt-get update && apt-get install --no-install-recommends -y \
    python-rosdep \
    python-rosinstall \
    python-vcstools
# Set up rosdep
RUN rosdep init
RUN rosdep update
# Install ROS-Base packages
RUN apt-get update && apt-get install -y ros-melodic-desktop-full

### Create catkin workspace ###
RUN mkdir -p /root/catkin_ws/src
WORKDIR /root/catkin_ws
RUN bash -c "source /opt/ros/melodic/setup.bash && \
             catkin_make -DCMAKE_BUILD_TYPE=Release"

# Load ROS environment at docker exec bash
RUN echo "source /opt/ros/melodic/setup.bash" >> /root/.bashrc
RUN echo "source /root/catkin_ws/devel/setup.bash" >> /root/.bashrc
                  
# Build
RUN /bin/bash -c "source /opt/ros/melodic/setup.bash && \
                  catkin_make -DCMAKE_BUILD_TYPE=Release"

# Install mask rcnn dependencies
COPY requirements.txt /root/requirements.txt
RUN  pip3 install --force-reinstall -r /root/requirements.txt

WORKDIR /root

# Load ROS environment at each run
COPY ./entrypoint.sh /root/entrypoint.sh
RUN chmod 777 /root/entrypoint.sh
ENTRYPOINT ["/root/entrypoint.sh"]

CMD ["bash"]


# From https://github.com/NVIDIA/nvidia-container-runtime/blob/master/README.md
# compute: required for CUDA and OpenCL applications.
# display: required for leveraging X11 display.
# graphics: required for running OpenGL and Vulkan applications.
# utility: required for using nvidia-smi and NVML.
# video: required for using the Video Codec SDK. Required by ZED SDK.
ENV NVIDIA_DRIVER_CAPABILITIES compute,display,graphics,utility,video

