version: '2.3'
services:
  ros_master:
    image: yubaoliu/root:ros-cuda10.2-cudnn7-ubuntu16
    container_name: ros_master
    command: roscore
    ports:
        - 11311:11311
    volumes:
        - root:/root

  terminal:
    image: yubaoliu/root:ros-cuda10.2-cudnn7-ubuntu16
    container_name: myterminal
    command: xterm
    runtime: nvidia
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
        - ROS_HOSTNAME=ros-cuda-cudnn7-ubuntu16
        - ROS_MASTER_URI=http://ros_master:11311
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - root:/root

volumes:
    root:
