version: '2.3'
services:
  ubuntu16-cuda9:
    image: yubaoliu/root:ros-cuda9.0-cudnn7-ubuntu16
    container_name: ros_master
    command: roscore
    runtime: nvidia
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
    volumes:
        # - root:/root
        - /tmp/.X11-unix:/tmp/.X11-unix:rw

  # terminal:
  #   image: yubaoliu/root:ros-cuda9.0-cudnn7-ubuntu16
  #   container_name: myterminal
  #   command: xterm
  #   runtime: nvidia
  #   environment:
  #       - DISPLAY
  #       - QT_X11_NO_MITSHM=1
  #       - ROS_HOSTNAME=ros-cuda-cudnn9.0-ubuntu16
  #       - ROS_MASTER_URI=http://ros_master:11311
  #   volumes:
  #       - /tmp/.X11-unix:/tmp/.X11-unix:rw
  #       - root:/root
# 
# volumes:
#     root:
