version: '2.3'
services:
  ros_master:
    image: yubaoliu/root:ros-cuda10.2-cudnn7-ubuntu18
    container_name: ros_master
    # stdin_open: true
    # tty: true
    command: roscore
    runtime: nvidia
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
        # - ROS_HOSTNAME=ros_master
        # - ROS_MASTER_URI=http://ros_master:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - root:/root
    entrypoint: /entrypoint-melodic.sh

  # terminal:
  #   image: yubaoliu/root:ros-cuda10.2-cudnn7-ubuntu18
  #   container_name: test-root-ubuntu18
  #   stdin_open: true
  #   tty: true
  #   # command: lxterminal
  #   runtime: nvidia
  #   environment:
  #       - DISPLAY
  #       - QT_X11_NO_MITSHM=1
  #       - ROS_HOSTNAME=terminal
  #       - ROS_MASTER_URI=http://ros_master:11311
  #   volumes:
  #       - /tmp/.X11-unix:/tmp/.X11-unix:rw
  #       - root:/root
  #   entrypoint: /entrypoint-melodic.sh
volumes:
    root:
