version: '2.3'
services:
  root_cuda10.2_ubuntu16:
    image: yubaoliu/root:ros-cuda10.2-cudnn7-ubuntu16
    build:
        context: .
        dockerfile: dockerfile-ubuntu16
        args:
            cuda_version: 10.2
            cudnn_version: 7
            ubuntu_version: 16.04
    runtime: nvidia
    stdin_open: true
    command:
        - roscore
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - root_cuda10.2_ubuntu16:/root

volumes:
    root_cuda10.2_ubuntu16:
