build-ubuntu16-cuda10.0:
	docker-compose -f docker-compose-ubuntu16-cuda10.0.yml build
run-ubuntu16-cuda10.0:
	docker-compose -f docker-compose-ubuntu16-cuda10.0.yml up
build-ubuntu18-cuda10.2:
	docker-compose -f docker-compose-ubuntu18-cuda10.2.yml build
run-ubuntu18-cuda10.2:
	docker-compose -f docker-compose-ubuntu18-cuda10.2.yml up
