version: '2.3'
services:
  ubuntu22-cuda12:
    image: slamai/ubuntu22:cuda12
    container_name: ubuntu22
    build:
        context: ..
        dockerfile: Ubuntu22/Dockerfile
        args:
            CUDA_VERSION: 12.9.1
            ROS_DISTRO: hummal
            CUDNN_VERSION: cudnn
    # user: "1000:1000"
    runtime: nvidia
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    command:
        # - xterm
        - lxterminal
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
    devices:
        - /dev/dri
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw
        - ~/.Xauthority:/root/.Xauthority
        # - /usr/lib/nvidia-cuda-toolkit:/usr/lib/nvidia-cuda-toolkit
        # - yubao_ubuntu20_cuda11:/root

# volumes:
#     yubao_ubuntu20_cuda11:
